title: messageformat
baseurl: /messageformat

permalink: pretty

remote_theme: just-the-docs/just-the-docs
color_scheme: custom

aux_links:
  'v2 docs': /messageformat/v2/
  'GitHub repo': https://github.com/messageformat/messageformat
logo: https://messageformat.github.io/messageformat/logo/messageformat.svg

gh_edit_link: true
gh_edit_link_text: Edit this page on GitHub
gh_edit_repository: https://github.com/messageformat/messageformat
gh_edit_branch: master
gh_edit_source: docs
gh_edit_view_mode: tree
